import{a as L,S as w,i as l}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const $="https://pixabay.com/api/",v="47358602-d5490533da2bc88f2f38f5bcb",q=15;async function S(o,t=1){const n=`${$}?key=${v}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${q}`,i=await L.get(n);if(i.status!==200)throw new Error("Failed to fetch images");return i.data}let u;function x(o){return o.map(({webformatURL:t,largeImageURL:n,tags:i,likes:e,views:r,comments:s,downloads:b})=>`
        <li class="gallery-list-item">
          <a href="${n}" class="gallery-list-link">
            <img class="gallery-img" src="${t}" alt="${i}" />
          </a>
          <div class="img-info">
            <p><b>Likes:</b> ${e}</p>
            <p><b>Views:</b> ${r}</p>
            <p><b>Comments:</b> ${s}</p>
            <p><b>Downloads:</b> ${b}</p>
          </div>
        </li>`).join("")}function E(o){o.innerHTML=""}function P(){u=new w(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250})}function I(){u&&u.refresh()}const d=document.querySelector(".search-form"),y=document.querySelector(".gallery"),g=document.querySelector(".loader"),c=document.querySelector(".load-more");let f="",a=1,p=0;const O=15;P();d.addEventListener("submit",async o=>{o.preventDefault();const t=d.elements.searchQuery.value.trim();if(!t){l.warning({title:"Warning",message:"Please enter a search query!"});return}f=t,a=1,E(y),c.style.display="none",await h(f,a)});c.addEventListener("click",async()=>{await h(f,a),C()});async function h(o,t){H();try{const n=await S(o,t);if(n.hits.length===0){l.error({title:"Error",message:"Sorry, there are no images matching your search query."}),m();return}p=n.totalHits;const i=x(n.hits);y.insertAdjacentHTML("beforeend",i),I(),m(),a*O>=p?(l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}),c.style.display="none"):c.style.display="flex",a+=1}catch(n){l.error({title:"Error",message:"Failed to load images. Please try again!"}),console.error("Error:",n)}finally{_()}}function H(){g.style.display="flex"}function _(){g.style.display="none"}function m(){d.elements.searchQuery.value=""}function C(){var t;const o=((t=y.firstElementChild)==null?void 0:t.getBoundingClientRect().height)||0;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
